"""empty message

Revision ID: 1b677a6dac86
Revises: 56d782f53a45
Create Date: 2020-10-05 12:14:09.802014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b677a6dac86'
down_revision = '56d782f53a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('Show_artistId_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_venueId_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Show', 'venueId')
    op.drop_column('Show', 'start')
    op.drop_column('Show', 'artistId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artistId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('venueId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venueId_fkey', 'Show', 'Venue', ['venueId'], ['id'])
    op.create_foreign_key('Show_artistId_fkey', 'Show', 'Artist', ['artistId'], ['id'])
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'start_time')
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
